### ISSUE TITLE
Is this library really not using a wrapper?

### ISSUE THREAD

**Issue by ciscoheat** [koriym/MaDci#1]
You refer to a wrapper question in the DCI FAQ, but this library seems to do just that. [Another FAQ question](http://fulloo.info/doku.php?id=i_found_a_library_that_claims_to_do_dci_how_can_i_know_that_it_does) for reference.

**Comment by koriym** [comment]
I do not claim this library is not using a wrapper. I recognised the author says it should be avoided but actually I just can not fully understand why is so important. (too bad !) Then I put the link for the notice.

I made PR #2 to clarify this issue.

**Comment by ciscoheat** [comment]
Thanks for that clarification, I've pointed it out before but people can be a bit offended. :)

The problem can occur when for example you're using a third party library that uses the `===` (identity comparison operator). If the wrapper object is passed to the library instead of the real roleplayer, the comparison will fail when it shouldn't. Also, if you pass the wrapper to a nested Context, now you have a Role wandering outside the Context, which is forbidden.

**Comment by koriym** [comment]
>> The problem can occur when for example you're using a third party library that uses the === (identity comparison operator).

`RolePlayer` is wrapper object. It attach or detach `Role` on demand. The `RolePlayer` keeps object ID, in that case, is it still porblem ?

**Comment by ciscoheat** [comment]
Yes it's still a problem, it relates to a known problem in OOP in general:
https://en.m.wikipedia.org/wiki/Schizophrenia_(object-oriented_programming)

**Comment by koriym** [comment]
`RealPlayer` object holds its own ID only in certain context, (not in other context) That can be a problematic in third library outside context because it can't identify the object. . .. Did I get that right?

> If the wrapper object is passed to the library instead of the real roleplayer,

I could not figure out this. "real roleplayer" IS wrapper object" ??? 🧐

**Comment by ciscoheat** [comment]
Here is the real roleplayer: https://github.com/koriym/MaDci/blob/master/src/RolePlayer.php#L14

And you bind the Roles like this: https://github.com/koriym/MaDci/blob/master/example/UseCase/TransferMoneyContext.php#L30

For any casual viewer of the code, `$this->sourceAccount` should now be the `Account` that was passed into it, but it's really a `RolePlayer` wrapping the `Account`. Now imagine that a third party library is comparing accounts with `===`. Any comparison with `$this->sourceAccount` and the actual account will fail, since they are not the same instance. The real account ("the real roleplayer") is located in `$this->sourceAccount->data`. Any attempt to alleviate this, for example by exposing the `data` property, is messy and error-prone. Always remember that one of the main goals with DCI is readability.

**Comment by koriym** [comment]
> Here is the real roleplayer: https://github.com/koriym/MaDci/blob/master/src/RolePlayer.php#L14
> The real account ("the real roleplayer") is located in $this->sourceAccount->data

Thank you for the clarification. I was not aware of this ! -> "the real roleplayer ==  The real accounts"  
(I may have underestimated the importance of object identification. Especially in language like PHP, in nothing shared architecture)

Thank you for the taking time and courteous reply.

**Comment by ciscoheat** [comment]
No problem, I'm very happy to help! If you want to do DCI in PHP, you can compile to PHP with Haxe and the DCI library I've made: https://github.com/ciscoheat/haxedci (it also has some tutorials if you're interested.)

**Comment by koriym** [comment]
Thanks for the link, will definitely give it a read. Much appreciate it!

**Comment by ciscoheat** [comment]
If you have any questions, let me know. :)
